namespace RNSketchCanvas {
    [default_interface]
    runtimeclass RNSketchCanvasModule : Windows.UI.Xaml.Controls.Canvas {
        RNSketchCanvasModule(Microsoft.ReactNative.IReactContext context);
        void UpdateProperties(Microsoft.ReactNative.IJSValueReader reader);
        void DispatchCommand(String commandId, Microsoft.ReactNative.IJSValueReader commandArgsReader);
    };
}
